apiVersion: v2
name: rdma-tools
home: "https://spidernet-io.github.io/charts"
#icon:
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: 12.5.5
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "12.5.5"
kubeVersion: ">= 1.16.0-0"
description: rdma test
sources:
  - "https://spidernet-io.github.io/charts"
keywords:
  - rdma
  - networking
